import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'
import { FileText, Download, Mail, Star, RefreshCw, Clock } from '@phosphor-icons/react'

interface SessionData {
  phase: string
  agreedIssue: string
  playerOneSteelMan: string
  playerTwoSteelMan: string
  playerOneStatement: string
  playerTwoStatement: string
  messages: Array<{
    id: string
    author: 'player1' | 'player2' | 'ai'
    content: string
    timestamp: number
  }>
  proposedResolution: string
  finalResolution: string
  sessionStarted: number
}

interface Props {
  sessionData: SessionData
  onReset: () => void
}

export default function SessionSummary({ sessionData, onReset }: Props) {
  const [rating, setRating] = useState<number>(0)
  const [feedback, setFeedback] = useState('')
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false)

  const duration = Math.round((Date.now() - sessionData.sessionStarted) / 1000 / 60) // minutes
  const aiInterventions = sessionData.messages.filter(m => m.author === 'ai')
  
  const handleSubmitFeedback = () => {
    // In a real app, this would submit to analytics
    console.log('Feedback submitted:', { rating, feedback })
    setFeedbackSubmitted(true)
  }

  const generateBattleReport = () => {
    const report = `
MIXITFIXIT BATTLE REPORT
=======================
Session Date: ${new Date(sessionData.sessionStarted).toLocaleString()}
Duration: ${duration} minutes
Status: ${sessionData.finalResolution ? 'RESOLVED' : 'UNRESOLVED'}

AGREED ISSUE
------------
${sessionData.agreedIssue}

STEEL-MAN DEMONSTRATIONS
------------------------
Player 1's Steel-Man of Player 2:
${sessionData.playerOneSteelMan}

Player 2's Steel-Man of Player 1:
${sessionData.playerTwoSteelMan}

LOCKED STATEMENTS
-----------------
Player 1's Statement:
${sessionData.playerOneStatement}

Player 2's Statement:
${sessionData.playerTwoStatement}

DISCUSSION HIGHLIGHTS
--------------------
Total Messages: ${sessionData.messages.filter(m => m.author !== 'ai').length}
AI Interventions: ${aiInterventions.length}

Key AI Interventions:
${aiInterventions.slice(0, 5).map((msg, i) => `${i + 1}. ${msg.content}`).join('\n')}

${sessionData.finalResolution ? `
FINAL RESOLUTION
----------------
${sessionData.finalResolution}

RESOLUTION STATUS: ✅ LOCKED AND AGREED UPON
` : `
RESOLUTION STATUS: ❌ NO MUTUAL AGREEMENT REACHED
`}

---
Generated by MixitFixit - Digital Thunderdome for Dysfunctional Relationships
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `mixitfixit-battle-report-${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText size={24} />
            Session Summary: Your Personalized Trauma Report
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-3 gap-4 mb-6">
            <div className="text-center p-4 bg-muted rounded-lg">
              <Clock size={24} className="mx-auto mb-2 text-muted-foreground" />
              <p className="text-2xl font-bold">{duration}</p>
              <p className="text-sm text-muted-foreground">minutes</p>
            </div>
            <div className="text-center p-4 bg-muted rounded-lg">
              <FileText size={24} className="mx-auto mb-2 text-muted-foreground" />
              <p className="text-2xl font-bold">{sessionData.messages.filter(m => m.author !== 'ai').length}</p>
              <p className="text-sm text-muted-foreground">messages</p>
            </div>
            <div className="text-center p-4 bg-muted rounded-lg">
              <Star size={24} className="mx-auto mb-2 text-muted-foreground" />
              <p className="text-2xl font-bold">{aiInterventions.length}</p>
              <p className="text-sm text-muted-foreground">AI interventions</p>
            </div>
          </div>

          <div className="space-y-6">
            <div>
              <h3 className="font-medium mb-2">Issue Resolution Status</h3>
              {sessionData.finalResolution ? (
                <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                  <div className="flex items-center gap-2 mb-2">
                    <Badge className="bg-green-100 text-green-800">RESOLVED</Badge>
                    <span className="text-sm text-green-700">Mutual agreement reached!</span>
                  </div>
                  <p className="text-sm text-green-800 whitespace-pre-wrap">{sessionData.finalResolution}</p>
                </div>
              ) : (
                <div className="p-4 bg-orange-50 border border-orange-200 rounded-lg">
                  <div className="flex items-center gap-2 mb-2">
                    <Badge className="bg-orange-100 text-orange-800">UNRESOLVED</Badge>
                    <span className="text-sm text-orange-700">No mutual agreement reached</span>
                  </div>
                  <p className="text-sm text-orange-800">
                    Sometimes the most mature thing is agreeing to disagree... or scheduling a rematch.
                  </p>
                </div>
              )}
            </div>

            <Separator />

            <div>
              <h3 className="font-medium mb-3">Battle Report Contents</h3>
              <div className="space-y-3 text-sm">
                <div className="flex items-center gap-2">
                  <Badge variant="outline">✓</Badge>
                  <span>Original agreed issue</span>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline">✓</Badge>
                  <span>Both steel-man demonstrations</span>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline">✓</Badge>
                  <span>Locked statements from both parties</span>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline">✓</Badge>
                  <span>Key AI interventions and observations</span>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline">✓</Badge>
                  <span>{sessionData.finalResolution ? 'Final locked resolution' : 'Session outcome summary'}</span>
                </div>
              </div>
            </div>

            <div className="flex gap-4">
              <Button onClick={generateBattleReport} className="flex-1">
                <Download size={16} className="mr-2" />
                Download Battle Report
              </Button>
              <Button onClick={onReset} variant="outline" className="flex-1">
                <RefreshCw size={16} className="mr-2" />
                Start New Session
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Feedback Section */}
      <Card>
        <CardHeader>
          <CardTitle>Session Feedback</CardTitle>
        </CardHeader>
        <CardContent>
          {feedbackSubmitted ? (
            <div className="text-center py-8">
              <Badge className="bg-green-100 text-green-800 mb-4">Feedback Submitted</Badge>
              <p className="text-muted-foreground">
                Thanks for your feedback. We'll use it to make future sessions less painful.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              <div>
                <label className="text-sm font-medium mb-2 block">
                  How much did this suck? (1 = torture, 5 = surprisingly helpful)
                </label>
                <div className="flex gap-2">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <Button
                      key={star}
                      variant={rating >= star ? "default" : "outline"}
                      size="sm"
                      onClick={() => setRating(star)}
                    >
                      <Star size={16} className={rating >= star ? "fill-current" : ""} />
                    </Button>
                  ))}
                </div>
              </div>

              <div>
                <label className="text-sm font-medium mb-2 block">
                  Any final thoughts? (Optional)
                </label>
                <Textarea
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                  placeholder="What worked? What didn't? Did the AI actually help or just annoy you more?"
                  className="min-h-20"
                />
              </div>

              <Button 
                onClick={handleSubmitFeedback}
                disabled={rating === 0}
                className="w-full"
              >
                Submit Feedback
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="bg-muted/50">
        <CardContent className="pt-6">
          <h3 className="font-medium mb-2">What Happens Next?</h3>
          <div className="space-y-2 text-sm text-muted-foreground">
            <p>• Your battle report contains everything that happened in this session</p>
            <p>• Keep it as a reference for future discussions about this topic</p>
            <p>• If you resolved the issue, use it as accountability documentation</p>
            <p>• If unresolved, consider what patterns emerged for next time</p>
            <p>• Remember: the goal isn't to win, it's to understand and improve</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}