import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { FileText, Download, ArrowCounterClockwise, Star } from '@phosphor-icons/react'

interface SessionData {
  phase: string
  agreedIssue: string
  playerOneSteelMan: string
  playerTwoSteelMan: string
  playerOneStatement: string
  playerTwoStatement: string
  messages: Array<{
    id: string
    author: 'player1' | 'player2' | 'ai'
    content: string
    timestamp: number
  }>
  proposedResolution: string
  finalResolution: string
  sessionStarted: number
}

interface SessionSummaryProps {
  sessionData: SessionData
  onReset: () => void
}

export default function SessionSummary({ sessionData, onReset }: SessionSummaryProps) {
  const sessionDuration = Math.round((Date.now() - sessionData.sessionStarted) / (1000 * 60))
  const aiInterventions = sessionData.messages.filter(m => m.author === 'ai').length
  const totalMessages = sessionData.messages.filter(m => m.author !== 'ai').length

  const generateReport = () => {
    const report = `
MIXITFIXIT BATTLE REPORT
========================

Session Date: ${new Date(sessionData.sessionStarted).toLocaleString()}
Duration: ${sessionDuration} minutes
Total Messages: ${totalMessages}
AI Interventions: ${aiInterventions}

THE ISSUE
---------
${sessionData.agreedIssue}

LOCKED STATEMENTS
-----------------
Player 1: ${sessionData.playerOneStatement}

Player 2: ${sessionData.playerTwoStatement}

STEEL-MANNING RESULTS
---------------------
Player 1's understanding of Player 2: ${sessionData.playerOneSteelMan}

Player 2's understanding of Player 1: ${sessionData.playerTwoSteelMan}

FINAL RESOLUTION
----------------
${sessionData.finalResolution}

DISCUSSION HIGHLIGHTS
---------------------
${sessionData.messages.length > 0 
  ? sessionData.messages.slice(-5).map(m => 
      `${m.author === 'ai' ? '[AI]' : `[${m.author.toUpperCase()}]`}: ${m.content}`
    ).join('\n\n')
  : 'No discussion messages recorded.'
}

---
Generated by MixitFixit - Digital Thunderdome for Dysfunctional Relationships
`

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `mixitfixit-battle-report-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getSuccessLevel = () => {
    if (sessionData.finalResolution) {
      if (aiInterventions < 3) return { level: 'Miraculous', color: 'bg-green-500', description: 'You actually managed to be civilized!' }
      if (aiInterventions < 6) return { level: 'Decent', color: 'bg-blue-500', description: 'Some AI guidance needed, but you got there' }
      return { level: 'Messy', color: 'bg-yellow-500', description: 'The AI had to work overtime, but resolution achieved' }
    }
    return { level: 'Ongoing', color: 'bg-gray-500', description: 'Still working on it...' }
  }

  const success = getSuccessLevel()

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText size={24} />
            Battle Report: Your Session Summary
          </CardTitle>
          <p className="text-muted-foreground">
            Here's your personalized trauma report (or triumph, if you actually figured it out).
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Session Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="text-center p-4 border rounded-lg">
              <div className="text-2xl font-bold text-primary">{sessionDuration}</div>
              <div className="text-sm text-muted-foreground">Minutes</div>
            </div>
            <div className="text-center p-4 border rounded-lg">
              <div className="text-2xl font-bold text-primary">{totalMessages}</div>
              <div className="text-sm text-muted-foreground">Messages</div>
            </div>
            <div className="text-center p-4 border rounded-lg">
              <div className="text-2xl font-bold text-destructive">{aiInterventions}</div>
              <div className="text-sm text-muted-foreground">AI Interventions</div>
            </div>
            <div className="text-center p-4 border rounded-lg">
              <Badge className={`${success.color} text-white`}>
                {success.level}
              </Badge>
              <div className="text-xs text-muted-foreground mt-1">{success.description}</div>
            </div>
          </div>

          {/* The Journey */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">The Journey</h3>
            
            <div className="space-y-3">
              <div className="flex items-start gap-3 p-3 border rounded-lg">
                <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center text-primary-foreground text-xs font-bold">1</div>
                <div>
                  <h4 className="font-medium">The Issue</h4>
                  <p className="text-sm text-muted-foreground">{sessionData.agreedIssue}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 border rounded-lg">
                <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center text-primary-foreground text-xs font-bold">2</div>
                <div>
                  <h4 className="font-medium">Steel-Manning Success</h4>
                  <p className="text-sm text-muted-foreground">
                    Both parties demonstrated they could understand each other's perspectives
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 border rounded-lg">
                <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center text-primary-foreground text-xs font-bold">3</div>
                <div>
                  <h4 className="font-medium">Locked Statements</h4>
                  <p className="text-sm text-muted-foreground">
                    Both positions were committed to digital stone
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 border rounded-lg">
                <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center text-primary-foreground text-xs font-bold">4</div>
                <div>
                  <h4 className="font-medium">Discussion Phase</h4>
                  <p className="text-sm text-muted-foreground">
                    {totalMessages} messages exchanged with {aiInterventions} AI reality checks
                  </p>
                </div>
              </div>

              {sessionData.finalResolution && (
                <div className="flex items-start gap-3 p-3 border-2 border-green-500 bg-green-50/50 rounded-lg">
                  <div className="w-6 h-6 rounded-full bg-green-500 flex items-center justify-center text-white text-xs font-bold">✓</div>
                  <div>
                    <h4 className="font-medium text-green-800">Final Resolution</h4>
                    <p className="text-sm text-green-700">{sessionData.finalResolution}</p>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-wrap gap-3 pt-4 border-t">
            <Button onClick={generateReport} variant="default" className="flex items-center gap-2">
              <Download size={16} />
              Download Full Report
            </Button>
            
            <Button onClick={onReset} variant="outline" className="flex items-center gap-2">
              <ArrowCounterClockwise size={16} />
              Start New Session
            </Button>
          </div>

          {/* Feedback */}
          <div className="pt-4 border-t">
            <h4 className="text-sm font-medium mb-3">How was this experience?</h4>
            <div className="flex gap-2">
              {[1, 2, 3, 4, 5].map(rating => (
                <Button 
                  key={rating}
                  variant="outline" 
                  size="sm"
                  className="flex items-center gap-1"
                  onClick={() => {
                    // In real app, this would submit feedback
                    console.log(`User rated: ${rating}`)
                  }}
                >
                  <Star size={12} />
                  {rating}
                </Button>
              ))}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              1 = "This was torture", 5 = "Actually helpful, weirdly"
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}